title: Petra Site
description: petracollegeacc website
theme: just-the-docs

url: https://petthepetra.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
