title: Petra College Account Main Page
description: github my beloved <3
theme: just-the-docs

url: https://petthepetra.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
